export const SUBMIT_AUTHENTICATION = 'SUBMIT_AUTHENTICATION';

export const FETCH_DATA = 'FETCH_DATA';

export const FETCH_ALBUMS = 'FETCH_ALBUMS';

export const FETCH_PORTFOLIO = 'FETCH_PORTFOLIO';

export const SUBMIT_ALBUM_DESCRIPTION = 'SUBMIT_ALBUM_DESCRIPTION';
