export const SHOW_REQUEST_ERROR = 'SHOW_REQUEST_ERROR';

export const HIDE_REQUEST_ERROR = 'HIDE_REQUEST_ERROR';

export const SIGN_ON = 'SIGN_ON';

export const SIGN_OUT = 'SIGN_OUT';

export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';

export const SET_ALBUMS = 'SET_ALBUMS';

export const SET_PORTFOLIO = 'SET_PORTFOLIO';

export const IS_LOADING_DATA = 'IS_LOADING_DATA';
